---
title: "Correlations SHAP Train/Test"
author: "Loecher"
date: "3/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

source("src/makeFigures_functions.R")
source("src/StroblData_ASTA2022.R")
source("src/helperFuns.R")
source("src/sim_utils.R")

library(ggpubr)
```

```{r, eval=FALSE}
#quick test
tmp = SHAPcorrs(r=0.15,n=50, M=2, alg = "rf")
```


```{r, eval=FALSE}
#another quick test
power_sim = data_simulation(n = 120,M = 5,relevance = 0.15)
shap_vals_oob <- power_sim[[1]]#M*n x 5
shap_vals_in <- power_sim[[2]]#M*n x 5
shap_avs_oob <- power_sim[[3]]#M x 5
shap_avs_in <- power_sim[[4]]#M x 5
shap_vals <- power_sim[[5]]#M*n x 5
shap_avs <- power_sim[[6]]#M x 5

```

## Random Forests 

### Strobl Power Simulation

```{r setParams}
rerun = FALSE
addSims = TRUE
#M is number of replication
n=120;M=75#for testing
#n=400;M=100
rdaFile = paste0("SimData/in_out_n",n,".rda")
```


```{r runSims, eval=rerun | addSims }
set.seed(20)
in_out_new=list()
r=0.15;cat("r=", r, "\n")
in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M)

r=0.25;cat("r=", r, "\n")
in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M)

r=0;cat("r=", r, "\n")
in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M)

if (addSims) {
  rdaFile_new = paste0("SimData/in_out_new_n",n,".rda")
  save(in_out_new, file = rdaFile)
  load(rdaFile)
  in_out = AppendSims(in_out, in_out_new)
} else {
  in_out = in_out_new
}
save(in_out, file = rdaFile)
```

```{r loadSims, eval=rerun}
load(rdaFile)
```

### SHAP values

```{r}
plotShrunkSHAP(in_out)
```

## XGBoost 

### Strobl Power Simulation

```{r setParams}
rerun = c(FALSE,TRUE)[2]
addSims = c(FALSE,TRUE)[1]
#M is number of replication
n=120;M=100#for testing
#n=400;M=100
rdaFile = paste0("SimData/in_out_xgb_n",n,".rda")
pars = list(n=n,M=M, alg = "xgb", genData = "strobl", desc="bla")
```


```{r runSims, eval=rerun | addSims }
in_out_new=list()
r=0.15;cat("r=", r, "\n")
in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M, alg = "xgb")

r=0.25;cat("r=", r, "\n")
in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M, alg = "xgb")

r=0;cat("r=", r, "\n")
in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M, alg = "xgb")

if (addSims) {
  rdaFile_new = paste0("SimData/in_out_xgb_new_n",n,".rda")
  save(in_out_new, file = rdaFile)
  load(rdaFile)
  in_out = AppendSims(in_out, in_out_new)
} else {
  in_out = in_out_new
}
in_out_xgb = in_out
save(in_out, pars, file = rdaFile)
```

```{r loadSims, eval=rerun}
load(rdaFile)
```

### SHAP values

```{r}
plotShrunkSHAP(in_out)
fname=paste0("../figures/ShrunkSHAP_xgb",Sys.Date(),".pdf")
ggsave(fname, height=5, width=5)
system(paste("cp ", fname, paste0("../figures/ShrunkSHAP_xgb.pdf")))
```

### MARS Power Simulation

#### all features are continuous

```{r}
in_out = RunSim(n=120,M=100,p=8,k=0,alg = "xgb",genData = "MARS", main ="")
```


```{r setParams}
rerun = c(FALSE,TRUE)[2]
addSims = c(FALSE,TRUE)[1]
#M is number of replication
n=120;M=100#for testing
#n=400;M=100
rdaFile = paste0("SimData/in_out_xgb_MARS_n",n,".rda")
pars = list(n=n,M=M, alg = "xgb", genData = "MARS", k=0, desc="all features continuous")
```


```{r runSims, eval=rerun | addSims }
#snr in 0.05, 0.09, 0.14, ..., 6.00
in_out_new=list()
for (r in c(0.001, 0.01, 0.1,0.25,1)){
  cat("r=", r, "\n")
  in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M, alg = "xgb", genData = "MARS", p=8)
}

if (addSims) {
  rdaFile_new = paste0("SimData/in_out_xgb_MARS_new_n",n,".rda")
  save(in_out_new, file = rdaFile)
  load(rdaFile)
  in_out = AppendSims(in_out, in_out_new)
} else {
  in_out = in_out_new
}
#in_out_xgb = in_out
save(in_out, pars, file = rdaFile)
```

```{r loadSims, eval=rerun}
load(rdaFile)
```

### plot SHAP values

```{r}
plotShrunkSHAP(in_out, main = "MARS, cont. ftrs")

fname=paste0("../figures/ShrunkSHAP_xgb_k0",Sys.Date(),".pdf")
ggsave(fname, height=5, width=5)
system(paste("cp ", fname, paste0("../figures/ShrunkSHAP_xgb_k0.pdf")))
```


#### informative features are discrete, no noise features

```{r}
k=rep(0,p);k[1:3]=2
in_out_discrete1 = RunSim(n=120,M=100,p=5,k=k,alg = "xgb",genData = "MARS", main ="")
```



```{r setParams}
rerun = c(FALSE,TRUE)[2]
addSims = c(FALSE,TRUE)[1]
#M is number of replication
n=120;M=50#for testing
#n=400;M=100
p=5
k=rep(0,p);k[1:3]=2
rdaFile = paste0("SimData/in_out_xgb_MARS_k2_n",n,"_p",p,".rda")
pars = list(n=n,M=M, alg = "xgb", genData = "MARS", k=k,p=p, desc="some informative features discrete")
```


```{r runSims, eval=rerun | addSims }
#snr in 0.05, 0.09, 0.14, ..., 6.00
in_out_new=list()
for (r in c(0.001, 0.005, 0.01, 0.02, 0.05,0.15)){
  cat("r=", r, "\n")
  in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M, alg = "xgb", genData = "MARS", p=p, k=k)
}

if (addSims) {
  rdaFile_new = paste0(rdaFile, "new.rda")
  save(in_out_new, file = rdaFile)
  load(rdaFile)
  in_out = AppendSims(in_out, in_out_new)
} else {
  in_out = in_out_new
}
#in_out_xgb = in_out
save(in_out, pars, file = rdaFile)
```

```{r loadSims, eval=rerun}
load(rdaFile)
```

### plot SHAP values

```{r}
plotShrunkSHAP(in_out, main ="MARS, k=2 for p=1:3", log_r=TRUE)

fname1 = paste0("../figures/in_out_xgb_MARS_k2_n",n,"_p",p,"_",Sys.Date(),".pdf")
fname2 = paste0("../figures/in_out_xgb_MARS_k2_n",n,"_p",p,".pdf")
#fname=paste0("../figures/ShrunkSHAP_xgb_k2_p7",Sys.Date(),".pdf")
ggsave(fname1, height=5, width=5)
system(paste("cp ", fname1, fname2))
```

#### informative features are discrete

```{r}
k=rep(0,p);k[1:3]=2
in_out_discrete2 = RunSim(n=120,M=100,p=7,k=k,alg = "xgb",genData = "MARS", main ="")
```

```{r setParams}
rerun = c(FALSE,TRUE)[2]
addSims = c(FALSE,TRUE)[1]
#M is number of replication
n=120;M=50#for testing
#n=400;M=100
p=7
k=rep(0,p);k[1:3]=2
rdaFile = paste0("SimData/in_out_xgb_MARS_k2_n",n,"_p",p,".rda")
pars = list(n=n,M=M, alg = "xgb", genData = "MARS", k=k,p=p, desc="some informative features discrete")
```


```{r runSims, eval=rerun | addSims }
#snr in 0.05, 0.09, 0.14, ..., 6.00
in_out_new=list()
for (r in c(0.001, 0.005, 0.01, 0.02, 0.05,0.15)){
  cat("r=", r, "\n")
  in_out_new[[as.character(r)]] = SHAPcorrs(r,n=n, M=M, alg = "xgb", genData = "MARS", p=p, k=k)
}

if (addSims) {
  rdaFile_new = paste0(rdaFile, "new.rda")
  save(in_out_new, file = rdaFile)
  load(rdaFile)
  in_out = AppendSims(in_out, in_out_new)
} else {
  in_out = in_out_new
}
#in_out_xgb = in_out
save(in_out, pars, file = rdaFile)
```

```{r loadSims, eval=rerun}
load(rdaFile)
```

### plot SHAP values

```{r}
plotShrunkSHAP(in_out, main ="MARS, k=2 for p=1:3", log_r=TRUE)

fname1 = paste0("../figures/in_out_xgb_MARS_k2_n",n,"_p",p,"_",Sys.Date(),".pdf")
fname2 = paste0("../figures/in_out_xgb_MARS_k2_n",n,"_p",p,".pdf")
ggsave(fname1, height=5, width=5)
system(paste("cp ", fname1, fname2))
```